Models/RecipeModel.cs
using System;
using System.Collections.Generic;

namespace MYFIRSTAPP.Models
{
    public class Recipe
    {
        public string Name {get; set;}
        public string Category {get; set;}
        public string Ingredients {get; set;}
    }

    public class RecipeDatabase : List<Recipe>
    {
        public RecipeDatabase()
        {
            Add (new Recipe() {Name="Almond Chutney", Category="Chutney", Ingredients="Red Chillies, Curry Leaves, Oil, Mustard Seeds, Almonds, Curd"});
            Add (new Recipe() {Name="Sunflower Seeds Chutney", Category="Chutney", Ingredients="Red Chillies, Curry Leaves, Oil, Mustard Seeds, Sunflower seeds, Chana dal, Lemon juice"});
            Add (new Recipe() {Name="Moong Dal Chutney", Category="Chutney", Ingredients="Red Chillies, Curry Leaves, Oil, Mustard Seeds, Sunflower seeds, Chana dal, Lemon juice"});
            Add (new Recipe() {Name="Kandipappu", Category="Chutney", Ingredients="Red Chillies, Curry Leaves, Oil, Mustard Seeds, Sunflower seeds, Chana dal, Lemon juice"});
            Add (new Recipe() {Name="Beet Root Leaves Chutney", Category="Chutney", Ingredients="Red Chillies, Curry Leaves, Oil, Mustard Seeds, Sunflower seeds, Chana dal, Lemon juice"});
            Add (new Recipe() {Name="Tomato Perugu Chutney", Category="Chutney", Ingredients="Red Chillies, Curry Leaves, Oil, Mustard Seeds, Sunflower seeds, Chana dal, Lemon juice"});
            Add (new Recipe() {Name="Vankaya Pachadi", Category="Chutney", Ingredients="Red Chillies, Curry Leaves, Oil, Mustard Seeds, Sunflower seeds, Chana dal, Lemon juice"});
            Add (new Recipe() {Name="Dosakaya Pachadi", Category="Chutney", Ingredients="Red Chillies, Curry Leaves, Oil, Mustard Seeds, Sunflower seeds, Chana dal, Lemon juice"});
            Add (new Recipe() {Name="Keera Dosakaya", Category="Chutney", Ingredients="Red Chillies, Curry Leaves, Oil, Mustard Seeds, Sunflower seeds, Chana dal, Lemon juice"});
            Add (new Recipe() {Name="Totakoora", Category="Sambhar", Ingredients="Red Chillies, Curry Leaves, Oil, Mustard Seeds, Sunflower seeds, Chana dal, Lemon juice"});
            Add (new Recipe() {Name="Keera Dosakaya", Category="Chutney", Ingredients="Red Chillies, Curry Leaves, Oil, Mustard Seeds, Sunflower seeds, Chana dal, Lemon juice"});
            Add (new Recipe() {Name="Keera Dosakaya", Category="Chutney", Ingredients="Red Chillies, Curry Leaves, Oil, Mustard Seeds, Sunflower seeds, Chana dal, Lemon juice"});

        }
    }
}

Controllers/ChutneyRecController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MYFIRSTAPP.Controllers 
{
    public class ChutneyRecController : Controller
    {
        public IActionResult AlmondChutney()
        {
            return View();
        }

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MyFirstApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

Controllers/RecipeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MYFIRSTAPP.Models;

namespace MYFIRSTAPP.Controllers 
{
    public class RecipeController : Controller
    {
        //Group the recipes by category
        public IActionResult Index()
        {
            List<Recipe> recs = new RecipeDatabase();
            List<Recipe> distinct = 
                recs
                .GroupBy(recipe => recipe.Category)
                .Select(g => g.First())
                .ToList();
            return View(distinct);
        }

        //Show the user recipes based on what category the user clicks
        public IActionResult CategorizedRecipes(string category)
        {
            List<Recipe> recs = new RecipeDatabase();
            List<Recipe> categorized_list = recs.FindAll(delegate(Recipe rec) { return rec.Category == category; });
            return View(categorized_list);
        }
        
        //Show the user detailed recipes based on what recipes the user clicks
        public IActionResult DetailedRecipes(string name)
        {
            List<Recipe> recs = new RecipeDatabase();
            List<Recipe> detailed_list = recs.FindAll(delegate(Recipe rec) { return rec.Name == name; });
            return View(detailed_list);
        }

    }
}

Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/indian1.jpg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to make food from the streets of Chennai
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/indian2.jpg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    From entrees to desserts, this is your one stop shop for indian cuisine recipes
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/indian3.jpg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                   Cook like the cooking they serve in buffets
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/indian4.jpg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Home cooked Indian meals recipes coming your way
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-6">
        <h2>My blog</h2>
    </div>
    <div class="col-md-6">
        <h2>This month's favorites</h2>
    </div>
</div>

Views/Recipe/CategorizedRecipes.cshtml
@model System.Collections.Generic.IEnumerable<MYFIRSTAPP.Models.Recipe>

        <h1>
        @Html.DisplayNameFor(Model => @Model.First().Category)
        </h1>
    


    <table class="chutneytable">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
        </tr>

     @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.ActionLink(item.Name, "DetailedRecipes", "Recipe", new {@name = item.Name}, null)
            </td>
            <td>
                @Html.ActionLink(item.Category, item.Category)
            </td>
        </tr>
        }
    </table>

Views/Recipe/DetailedRecipes.cshtml
@model System.Collections.Generic.IEnumerable<MYFIRSTAPP.Models.Recipe>

    <h1>
        @Html.DisplayNameFor(Model => @Model.First().Name)
    </h1>

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Ingredients)
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink(item.Ingredients, item.Ingredients)
                </td>

            </tr>
        }
        </table>

Views/Recipe/Index.cshtml
@model System.Collections.Generic.IEnumerable<MYFIRSTAPP.Models.Recipe>
    <h1>Recipe Details</h1>

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink(item.Category, item.Category)
                </td>

            </tr>
        }
        </table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyFirstApp</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">MyFirstApp</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Recipe" asp-action="Index">Recipes</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - MyFirstApp</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.3.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>